version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - bump:patch

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    labels:
      - bump:patch
